package com.l5rcm.companion.data.save.qr

import com.l5rcm.companion.data.save.SaveParser
import com.l5rcm.companion.resourceText
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.util.Base64
import java.util.zip.CRC32
import java.util.zip.GZIPOutputStream
import kotlin.random.Random

class QrChunkAssemblerTest {

    // --- writer side, mirroring docs/QR_IMPORT_FORMAT.md, used to build test frames ---

    private fun gzip(bytes: ByteArray): ByteArray =
        ByteArrayOutputStream().also { bos -> GZIPOutputStream(bos).use { it.write(bytes) } }.toByteArray()

    private fun frames(json: String, id: String = "ABC123", chunkChars: Int = 700): List<String> {
        val blob = gzip(json.toByteArray(Charsets.UTF_8))
        val b64 = Base64.getEncoder().encodeToString(blob)
        val crc = CRC32().apply { update(blob) }.value.toString(16).padStart(8, '0')
        val parts = b64.chunked(chunkChars)
        return parts.mapIndexed { seq, c -> "L5RQR1|$id|$seq|${parts.size}|$crc|$c" }
    }

    private fun feedAll(frames: List<String>): String? {
        val a = QrChunkAssembler()
        var result: String? = null
        frames.forEach { a.offer(it)?.let { json -> result = json } }
        return result
    }

    @Test
    fun reassemblesInOrder() {
        val json = """{"name":"Sumata","clan":"crane"}"""
        // small chunk forces multiple frames
        assertEquals(json, feedAll(frames(json, chunkChars = 8)))
    }

    @Test
    fun reassemblesOutOfOrderAndIgnoresDuplicates() {
        val json = resourceText("saves/doji_sumata.l5r")
        val fr = frames(json, chunkChars = 700)
        val withDupes = (fr + fr).shuffled(Random(42))
        val decoded = feedAll(withDupes)
        assertEquals(json, decoded)
        // and the decoded text is a valid save
        assertEquals("Sumata", SaveParser.parse(decoded!!).name)
    }

    @Test
    fun incompleteTransferYieldsNoResult() {
        val fr = frames(resourceText("saves/doji_sumata.l5r"), chunkChars = 700)
        val a = QrChunkAssembler()
        // feed all but the last frame
        fr.dropLast(1).forEach { assertNull(a.offer(it)) }
        assertEquals(fr.size, a.progress.total)
        assertEquals(fr.size - 1, a.progress.collected)
    }

    @Test
    fun ignoresForeignAndMalformedFrames() {
        val a = QrChunkAssembler()
        assertNull(a.offer("https://example.com/not-a-frame"))
        assertNull(a.offer("L5RQR1|ID|0"))                 // too few fields
        assertNull(a.offer("L5RQR1|ID|x|2|00000000|data")) // non-numeric seq
        assertNull(a.offer("L5RQR1|ID|3|2|00000000|data")) // seq out of range
    }

    @Test(expected = QrTransferException::class)
    fun rejectsUnsupportedVersion() {
        QrChunkAssembler().offer("L5RQR2|ID|0|1|00000000|AAAA")
    }

    @Test(expected = QrTransferException::class)
    fun rejectsCrcMismatch() {
        val blob = gzip("""{"name":"x"}""".toByteArray(Charsets.UTF_8))
        val parts = Base64.getEncoder().encodeToString(blob).chunked(8)
        val a = QrChunkAssembler()
        // valid data but a deliberately wrong crc in every frame
        parts.forEachIndexed { seq, c -> a.offer("L5RQR1|ID|$seq|${parts.size}|deadbeef|$c") }
    }

    /**
     * Authoritative cross-implementation contract: these exact frames (generated by the
     * Python writer with gzip mtime=0) MUST decode to this exact payload. See
     * docs/QR_IMPORT_FORMAT.md §7.
     */
    @Test
    fun decodesGoldenVector() {
        val goldenFrames = listOf(
            "L5RQR1|7F3A|0|4|97dae91d|H4sIAAAAAAACCqtWKkstKs7Mz1OyUjLR",
            "L5RQR1|7F3A|1|4|97dae91d|M1DSUUrOSCxSsqpWykvMTQUKuuRnZSqE",
            "L5RQR1|7F3A|2|4|97dae91d|pBaXgKRyEkHqkosS81KVanWUElPKEvOK",
            "L5RQR1|7F3A|3|4|97dae91d|layiY2sBLlLr40gAAAA=",
        )
        assertEquals(
            """{"version":"4.0","char":{"name":"Doji Test","clan":"crane"},"advans":[]}""",
            feedAll(goldenFrames),
        )
    }
}
